prompt --application/pages/page_00300
begin
--   Manifest
--     PAGE: 00300
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.11'
,p_default_workspace_id=>2200408020639491
,p_default_application_id=>300
,p_default_id_offset=>31969957811146237
,p_default_owner=>'JASOLAR'
);
wwv_flow_imp_page.create_page(
 p_id=>300
,p_name=>unistr('\5206\5E73\53F0\7BA1\7406\540E\53F0')
,p_alias=>'SUB_PLATFORM_ADMIN'
,p_step_title=>unistr('\5206\5E73\53F0\7BA1\7406\540E\53F0')
,p_autocomplete_on_off=>'OFF'
,p_group_id=>wwv_flow_imp.id(9731818236280992258)
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'function p300RefreshReport() {',
'    var region = apex.region("p300-report");',
'    if (region && region.refresh) {',
'        region.refresh();',
'        return;',
'    }',
'',
'    window.location.reload();',
'}',
'',
'function p300ApplyFilter() {',
'    var keywordEl = document.getElementById("p300-keyword");',
'    var tableEl = document.getElementById("report_table_p300-report");',
'    if (!tableEl) {',
'        return;',
'    }',
'',
'    var keyword = keywordEl ? keywordEl.value.trim().toLowerCase() : "";',
'    var rows = tableEl.querySelectorAll("tbody tr");',
'',
'    Array.prototype.forEach.call(rows, function (row) {',
'        var haystack = (row.innerText || row.textContent || "").toLowerCase();',
'        row.style.display = !keyword || haystack.indexOf(keyword) > -1 ? "" : "none";',
'    });',
'}',
'',
'function p300Delete(systemId) {',
unistr('    if (!window.confirm("\786E\8BA4\5220\9664\8BE5\5B50\5E73\53F0\5417\FF1F")) {'),
'        return;',
'    }',
'    apex.server.process("P300_DELETE_SUB_PLATFORM", {',
'        x01: systemId',
'    }, {',
'        dataType: "json",',
'        success: function (data) {',
'            if (data && data.code === "200") {',
unistr('                apex.message.showPageSuccess("\5220\9664\6210\529F");'),
'                p300RefreshReport();',
'                return;',
'            }',
unistr('            apex.message.alert((data && data.message) || "\5220\9664\5931\8D25");'),
'        },',
'        error: function () {',
unistr('            apex.message.alert("\5220\9664\5931\8D25");'),
'        }',
'    });',
'}',
'',
'function p300OpenDialog(targetUrl, titleText) {',
'    if (!targetUrl) {',
'        return;',
'    }',
'    var dialogTrigger = apex.jQuery("#p300-app");',
'',
'    apex.navigation.dialog(targetUrl, {',
unistr('        title: titleText || "\7EF4\62A4\5206\5E73\53F0",'),
'        height: "500",',
'        width: "480",',
'        modal: true',
'    }, "t-Dialog-page--standard", dialogTrigger);',
'}',
'',
'function p300Create() {',
unistr('    p300OpenDialog("f?p=&APP_ID.:301:&APP_SESSION.::&DEBUG.:301::", "\65B0\589E\5E73\53F0");'),
'}',
'',
'function p300Edit(editUrl) {',
unistr('    p300OpenDialog(editUrl, "\4FEE\6539\5E73\53F0\4FE1\606F");'),
'}',
'',
'apex.jQuery(function () {',
'    var keywordEl = document.getElementById("p300-keyword");',
'    if (!keywordEl) {',
'        return;',
'    }',
'',
'    p300ApplyFilter();',
'',
'    document.addEventListener("click", function (evt) {',
'        var rawTarget = evt.target;',
'        var target = rawTarget && rawTarget.closest ? rawTarget.closest("button") : rawTarget;',
'        if (!target) {',
'            return;',
'        }',
'        if (target && target.id === "p300-create-btn") {',
'            p300Create();',
'            return;',
'        }',
'        if (target && target.dataset && target.dataset.act === "delete") {',
'            p300Delete(target.dataset.id);',
'            return;',
'        }',
'        if (target && target.dataset && target.dataset.act === "edit") {',
'            p300Edit(target.dataset.url);',
'            return;',
'        }',
'    });',
'',
'    keywordEl.addEventListener("input", p300ApplyFilter);',
'',
'    apex.jQuery("#p300-report").on("apexafterrefresh", p300ApplyFilter);',
'    apex.jQuery("#p300-app").on("apexafterclosedialog", p300RefreshReport);',
'});'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'.t-Body-nav,',
'#t_Body_nav,',
'#t_TreeNav,',
'#t_Button_navControl,',
'.t-BreadcrumbRegion,',
'.t-Body-title {',
'    display: none !important;',
'}',
'.t-PageBody .t-Body-main {',
'    margin-left: 0 !important;',
'}',
'.t-Body-content {',
'    background: #f0f2f5;',
'}',
'.t-Body-contentInner {',
'    padding-top: 0 !important;',
'}',
'.t-Region.p300-layout-region,',
'.t-Region.p300-report-region {',
'    background: transparent;',
'    border: none;',
'    box-shadow: none;',
'}',
'.t-Region.p300-layout-region .t-Region-bodyWrap,',
'.t-Region.p300-layout-region .t-Region-body {',
'    background: transparent;',
'}',
'.p300-wrap {',
'    background: transparent;',
'}',
'.p300-main {',
'    padding: 24px 32px 20px;',
'}',
'.p300-head {',
'    display: flex;',
'    justify-content: space-between;',
'    align-items: center;',
'    gap: 16px;',
'    margin-bottom: 20px;',
'}',
'.p300-page-title {',
'    display: flex;',
'    align-items: center;',
'    gap: 8px;',
'}',
'.p300-page-title .fa {',
'    color: #1890ff;',
'    font-size: 22px;',
'}',
'.p300-head .t-Button {',
'    height: 36px;',
'    line-height: 34px;',
'    padding: 0 16px;',
'    border-radius: 6px;',
'    border: none;',
'    box-shadow: none;',
'    background: #1890ff !important;',
'    color: #ffffff !important;',
'    font-size: 14px;',
'    font-weight: 500;',
'    transition: all .2s ease;',
'}',
'.p300-head .t-Button:hover {',
'    background: #40a9ff !important;',
'    box-shadow: 0 2px 8px rgba(24,144,255,0.30);',
'}',
'.p300-title {',
'    margin: 0;',
'    font-size: 20px;',
'    line-height: 1.2;',
'    font-weight: 600;',
'    color: #333333;',
'}',
'.p300-search-row {',
'    display: none;',
'}',
'.p300-search {',
'    width: 360px;',
'    max-width: 100%;',
'    height: 40px;',
'    border: 1px solid #d9d9d9;',
'    border-radius: 6px;',
'    padding: 0 12px;',
'    font-size: 14px;',
'    color: #333333;',
'    background: #ffffff;',
'}',
'.p300-table-wrap {',
'    margin: 0 32px 24px;',
'    background: #ffffff;',
'    border-radius: 10px;',
'    overflow: hidden;',
'    box-shadow: 0 1px 4px rgba(0,0,0,0.06);',
'}',
'.p300-report-region {',
'    margin-top: 0;',
'}',
'.p300-report-region .t-Report-report {',
'    width: 100%;',
'    border-collapse: collapse;',
'}',
'.p300-report-region .t-Report-colHead {',
'    background: #fafafa;',
'    color: #666666;',
'    font-size: 13px;',
'    font-weight: 500;',
'    text-align: left;',
'    padding: 13px 16px;',
'    border-bottom: 1px solid #f0f0f0;',
'}',
'.p300-report-region .t-Report-cell {',
'    padding: 14px 16px;',
'    border-bottom: 1px solid #f5f5f5;',
'    color: #333333;',
'    font-size: 14px;',
'    vertical-align: middle;',
'}',
'.p300-report-region .t-Report-report tbody tr:hover .t-Report-cell {',
'    background: #fafafa;',
'}',
'.p300-admin-tag {',
'    display: inline-flex;',
'    align-items: center;',
'    gap: 4px;',
'    padding: 3px 10px;',
'    border-radius: 4px;',
'    background: #e6f7ff;',
'    color: #1890ff;',
'    font-size: 12px;',
'    font-weight: 500;',
'    margin-right: 6px;',
'}',
'.p300-admin-tag .fa {',
'    font-size: 12px;',
'}',
'.p300-admin-text {',
'    color: #cccccc;',
'    font-size: 13px;',
'    font-style: italic;',
'}',
'.p300-code {',
'    display: inline-flex;',
'    flex-direction: column;',
'    gap: 2px;',
'}',
'.p300-code-main {',
'    font-family: "SF Mono", Monaco, monospace;',
'    font-size: 13px;',
'    font-weight: 500;',
'    color: #1890ff;',
'}',
'.p300-code-sub {',
'    color: #999999;',
'    font-size: 12px;',
'    line-height: 1.3;',
'}',
'.p300-remark {',
'    display: inline-block;',
'    max-width: 280px;',
'    color: #666666;',
'    font-size: 13px;',
'    line-height: 1.5;',
'}',
'.p300-remark.is-empty {',
'    color: #cccccc;',
'    font-size: 13px;',
'    font-style: italic;',
'}',
'.p300-time {',
'    color: #999999;',
'    font-size: 13px;',
'    white-space: nowrap;',
'}',
'.p300-report-region .t-Report-report tbody tr:last-child .t-Report-cell {',
'    border-bottom: none;',
'}',
'.p300-op-cell {',
'    display: flex;',
'    gap: 8px;',
'    white-space: nowrap;',
'}',
'.p300-op {',
'    padding: 6px 12px;',
'    border: 1px solid #d9d9d9;',
'    border-radius: 6px;',
'    background: #ffffff;',
'    cursor: pointer;',
'    display: inline-flex;',
'    align-items: center;',
'    gap: 4px;',
'    color: #666666;',
'    font-size: 13px;',
'    transition: all .2s ease;',
'}',
'.p300-op .fa {',
'    font-size: 14px;',
'}',
'.p300-op:hover,',
'.p300-op-edit:hover {',
'    border-color: #1890ff;',
'    color: #1890ff;',
'}',
'.p300-op-delete:hover {',
'    border-color: #ff4d4f;',
'    color: #ff4d4f;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'03'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12968061084377707527)
,p_plug_name=>unistr('\9762\5305\5C51')
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(9731614793730394034)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(9763469109414540199)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(9731677229303394079)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12968061084377707528)
,p_plug_name=>unistr('\5206\5E73\53F0\5217\8868')
,p_region_css_classes=>'p300-layout-region'
,p_region_template_options=>'#DEFAULT#:t-Region--hideHeader:t-Region--noPadding'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_imp.id(9731592608628394027)
,p_plug_display_sequence=>20
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div id="p300-app" class="p300-wrap">',
'  <div class="p300-main">',
'    <div class="p300-head">',
'      <div class="p300-page-title">',
'        <span class="fa fa-th-large" aria-hidden="true"></span>',
unistr('        <h2 class="p300-title">\5E73\53F0\5217\8868</h2>'),
'      </div>',
unistr('      <button id="p300-create-btn" type="button" class="t-Button t-Button--hot">+ \65B0\589E\5E73\53F0</button>'),
'    </div>',
'    <div class="p300-search-row">',
unistr('      <input id="p300-keyword" class="p300-search" type="text" placeholder="\641C\7D22\5E73\53F0\7F16\53F7\3001\540D\79F0\6216\7BA1\7406\5458..." />'),
'    </div>',
'  </div>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(12968061084377707532)
,p_plug_name=>unistr('\5206\5E73\53F0\62A5\8868')
,p_region_name=>'p300-report'
,p_region_css_classes=>'p300-table-wrap p300-report-region'
,p_region_template_options=>'#DEFAULT#:t-Region--hideHeader:t-Region--noPadding'
,p_component_template_options=>'#DEFAULT#:t-Report--stretch:t-Report--staticRowColors:t-Report--rowHighlight:t-Report--horizontalBorders:t-Report--hideNoPagination'
,p_plug_template=>wwv_flow_imp.id(9731592608628394027)
,p_plug_display_sequence=>30
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_row_count number := 0;',
'',
'    procedure p(p_text in varchar2) is',
'    begin',
'        sys.htp.p(p_text);',
'    end;',
'begin',
'    p(''<div class="p300-table-wrap p300-report-region">'');',
'    p(''<table id="report_table_p300-report" class="t-Report-report" role="table">'');',
'    p(''<thead><tr>'' ||',
'      ''<th class="t-Report-colHead" scope="col">'' || to_char(unistr(''\5E73\53F0\7F16\53F7'')) || ''</th>'' ||',
'      ''<th class="t-Report-colHead" scope="col">'' || to_char(unistr(''\4E1A\52A1\7BA1\7406\5458'')) || ''</th>'' ||',
'      ''<th class="t-Report-colHead" scope="col">'' || to_char(unistr(''\521B\5EFA\65F6\95F4'')) || ''</th>'' ||',
'      ''<th class="t-Report-colHead" scope="col">'' || to_char(unistr(''\5907\6CE8'')) || ''</th>'' ||',
'      ''<th class="t-Report-colHead" scope="col">'' || to_char(unistr(''\64CD\4F5C'')) || ''</th></tr></thead><tbody>'');',
'',
'    for r in (',
'        select ''fmp'' || to_char(s.system_id) as system_code,',
'               s.system_name,',
'               nvl((',
'                    select listagg(''<span class="p300-admin-tag"><span class="fa fa-user-o" aria-hidden="true"></span><span>'' || apex_escape.html(x.admin_name) || ''</span></span>'', '''') within group (order by x.admin_name)',
'                      from (select distinct nvl(bu.name, sc.range_id) as admin_name',
'                              from sts_scope sc',
'                              left join basic_user bu',
'                                on bu.tenant_id = to_number(nvl(nullif(v(''USER_TENANT''), ''''), ''0''))',
'                               and bu.del_flag = 0',
'                               and (sc.range_id = nvl(bu.union_id, to_char(bu.user_id))',
'                                    or sc.range_id = to_char(bu.user_id))',
'                             where sc.reference_type = ''SYSTEM''',
'                               and sc.permissions_type = ''MANAGE''',
'                               and sc.range_type = ''USER''',
'                               and sc.reference_id = s.system_id',
'                           ) x',
'               ), ''<span class="p300-admin-text">-</span>'') as admin_html,',
'               to_char(nvl(s.creation_date, sysdate), ''yyyy-mm-dd hh24:mi:ss'') as creation_date,',
'               case',
'                   when trim(s.remark) is null then ''<span class="p300-remark is-empty">'' || to_char(unistr(''\6682\65E0\5907\6CE8'')) || ''</span>''',
'                   else ''<span class="p300-remark">'' || apex_escape.html(s.remark) || ''</span>''',
'               end as remark_html,',
'               ''<div class="p300-op-cell">'' ||',
'               ''<button type="button" class="p300-op p300-op-edit" data-act="edit" data-url="'' || apex_escape.html_attribute(apex_page.get_url(p_page => 301, p_items => ''P301_SYSTEM_ID'', p_values => s.system_id)) || ''"><span class="fa fa-pencil" aria'
||'-hidden="true"></span><span>'' || to_char(unistr(''\7F16\8F91'')) || ''</span></button>'' ||',
'               ''<button type="button" class="p300-op p300-op-delete" data-act="delete" data-id="'' || s.system_id || ''"><span class="fa fa-trash-o" aria-hidden="true"></span><span>'' || to_char(unistr(''\5220\9664'')) || ''</span></button></div>'' as operation_html',
'          from sts_system s',
'         where nvl(s.del_flag, 0) = 0',
'           and nvl(s.is_enable, 1) = 1',
'         order by s.system_id',
'    ) loop',
'        l_row_count := l_row_count + 1;',
'        p(''<tr>'' ||',
'          ''<td class="t-Report-cell"><div class="p300-code"><span class="p300-code-main">'' || apex_escape.html(r.system_code) || ''</span><span class="p300-code-sub">'' || apex_escape.html(r.system_name) || ''</span></div></td>'' ||',
'          ''<td class="t-Report-cell">'' || r.admin_html || ''</td>'' ||',
'          ''<td class="t-Report-cell"><span class="p300-time">'' || apex_escape.html(r.creation_date) || ''</span></td>'' ||',
'          ''<td class="t-Report-cell">'' || r.remark_html || ''</td>'' ||',
'          ''<td class="t-Report-cell">'' || r.operation_html || ''</td></tr>'');',
'    end loop;',
'',
'    if l_row_count = 0 then',
'        p(''<tr><td class="t-Report-cell p300-admin-text" colspan="5">'' || to_char(unistr(''\6682\65E0\6570\636E'')) || ''</td></tr>'');',
'    end if;',
'',
'    p(''</tbody></table>'');',
'    p(''</div>'');',
'end;'))
,p_plug_source_type=>'NATIVE_PLSQL'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(12968061084377707531)
,p_process_sequence=>30
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'P300_DELETE_SUB_PLATFORM'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    v_system_id       number;',
'    v_next_system_id  number;',
'begin',
'    v_system_id := to_number(apex_application.g_x01);',
'',
'    update sts_system',
'       set del_flag = 1,',
'           is_enable = 0,',
'           updated_by = to_number(v(''MPF_USER_ID'')),',
'           update_date = sysdate',
'     where system_id = v_system_id',
'       and nvl(del_flag, 0) = 0;',
'',
'    apex_json.open_object;',
'    if sql%rowcount = 0 then',
'        apex_json.write(''code'', ''404'');',
unistr('        apex_json.write(''message'', ''\5B50\5E73\53F0\4E0D\5B58\5728\6216\5DF2\5220\9664'');'),
'        apex_json.close_object;',
'        return;',
'    end if;',
'',
'    delete from sts_scope',
'     where reference_type = ''SYSTEM''',
'       and permissions_type = ''MANAGE''',
'       and reference_id = v_system_id;',
'',
'    if to_char(v(''SYSTEM_ID'')) = to_char(v_system_id) then',
'        select min(system_id)',
'          into v_next_system_id',
'          from sts_system',
'         where nvl(del_flag, 0) = 0',
'           and nvl(is_enable, 1) = 1;',
'',
'        apex_util.set_session_state(''SYSTEM_ID'', nvl(v_next_system_id, 1));',
'    end if;',
'',
'    commit;',
'    apex_json.write(''code'', ''200'');',
unistr('    apex_json.write(''message'', ''\5220\9664\6210\529F'');'),
'    apex_json.close_object;',
'exception',
'    when others then',
'        rollback;',
'        apex_json.open_object;',
'        apex_json.write(''code'', ''500'');',
unistr('        apex_json.write(''message'', ''\5220\9664\5931\8D25'');'),
'        apex_json.close_object;',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>13061466163549059216
);
wwv_flow_imp.component_end;
end;
/
