BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "FMP_FILE_TENANT_SYSTEM_PARENT_SORT_INDEX" ON "FMP_FILE" ("TENANT_ID", "SYSTEM_ID", "PARENT_FOLDER_ID", "DEL_FLAG", "SORT_NUM", "FILE_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
