BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "FMP_FILE_FILE_ID_TENANT_PARENT_INDEX" ON "FMP_FILE" ("FILE_ID", "TENANT_ID", "DEL_FLAG", "PARENT_FOLDER_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
