prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/pwa/shortcuts/快速开始.sql
@@application/shared_components/pwa/shortcuts/设计.sql
@@application/shared_components/pwa/shortcuts/组件.sql
@@application/shared_components/pwa/shortcuts/图标.sql
@@application/shared_components/pwa/shortcuts/参考.sql
@@application/shared_components/pwa/screenshots/screenshot_1_png.sql
@@application/shared_components/pwa/screenshots/screenshot_2_png.sql
@@application/shared_components/pwa/screenshots/screenshot_3_png.sql
@@application/shared_components/pwa/screenshots/screenshot_4_png.sql
@@application/shared_components/pwa/screenshots/screenshot_5_png.sql
@@application/shared_components/navigation/lists/导航栏.sql
@@application/shared_components/navigation/lists/ut_application_导航.sql
@@application/shared_components/navigation/lists/ut_向导进度.sql
@@application/shared_components/navigation/lists/ut_移动端.sql
@@application/shared_components/navigation/lists/ut_sample_媒体列表.sql
@@application/shared_components/navigation/lists/badge_list_sample.sql
@@application/shared_components/navigation/lists/ut_utility_类.sql
@@application/shared_components/navigation/lists/ut_tools.sql
@@application/shared_components/navigation/lists/ut_javascript_utilities.sql
@@application/shared_components/navigation/lists/ut_设计_patterns.sql
@@application/shared_components/navigation/lists/ut_sample_导航_mega_menu.sql
@@application/shared_components/navigation/lists/ut_sample_导航_menu.sql
@@application/shared_components/navigation/lists/ut_sample_卡片_list.sql
@@application/shared_components/navigation/lists/ut_sample_链接列表.sql
@@application/shared_components/navigation/lists/ut_sample_菜单栏_list.sql
@@application/shared_components/navigation/lists/template_pages.sql
@@application/shared_components/navigation/lists/templates_组件.sql
@@application/shared_components/navigation/lists/ut_sample_弹出菜单.sql
@@application/shared_components/navigation/lists/ut_sample_弹出菜单_操作.sql
@@application/shared_components/navigation/lists/ut_get_开始ed_导航.sql
@@application/shared_components/navigation/lists/向导进度_list.sql
@@application/shared_components/navigation/lists/ut_sample_选项卡_list.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/demo_buttonbuilder_js.sql
@@application/shared_components/files/demo_icons_js.sql
@@application/shared_components/files/demo_iconsearch_js.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/theme_styles_redwood_light_png.sql
@@application/shared_components/files/theme_styles_vita_png.sql
@@application/shared_components/files/theme_styles_vita_dark_png.sql
@@application/shared_components/files/theme_styles_vita_red_png.sql
@@application/shared_components/files/theme_styles_vita_slate_png.sql
@@application/shared_components/files/demo_demo_js.sql
@@application/shared_components/files/pwa_screenshot_1_png.sql
@@application/shared_components/files/pwa_screenshot_2_png.sql
@@application/shared_components/files/pwa_screenshot_3_png.sql
@@application/shared_components/files/pwa_screenshot_4_png.sql
@@application/shared_components/files/pwa_screenshot_5_png.sql
@@application/shared_components/files/pwa_shortcut_icon_10_png.sql
@@application/shared_components/files/pwa_shortcut_icon_20_png.sql
@@application/shared_components/files/pwa_shortcut_icon_30_png.sql
@@application/shared_components/files/pwa_shortcut_icon_40_png.sql
@@application/shared_components/files/pwa_shortcut_icon_50_png.sql
@@application/shared_components/files/demo_iconsearch_min_js.sql
@@application/shared_components/files/demo_icons_min_js.sql
@@application/shared_components/files/demo_buttonbuilder_min_js.sql
@@application/shared_components/files/demo_demo_min_js.sql
@@application/shared_components/files/bookmarklet_html.sql
@@application/shared_components/files/bookmarklet_js.sql
@@application/shared_components/files/img_persona_female01_apex_png.sql
@@application/shared_components/files/img_chatbots_jpg.sql
@@application/shared_components/files/img_persona_male01_apex_png.sql
@@application/shared_components/files/img_analyze_jpg.sql
@@application/shared_components/files/img_best_in_class_jpg.sql
@@application/shared_components/files/img_persona_male03_png.sql
@@application/shared_components/files/img_app_user_jpg.sql
@@application/shared_components/files/img_adaptable_jpg.sql
@@application/shared_components/files/img_diversity_jpg.sql
@@application/shared_components/files/img_construction_and_engineering_jpg.sql
@@application/shared_components/files/img_discovery_jpg.sql
@@application/shared_components/files/img_hr_jpg.sql
@@application/shared_components/files/img_emerging_tech_jpg.sql
@@application/shared_components/files/img_persona_female03_png.sql
@@application/shared_components/files/img_persona_female04_oracle_png.sql
@@application/shared_components/files/img_blockchain_jpg.sql
@@application/shared_components/files/img_collaboration_jpg.sql
@@application/shared_components/files/img_ai_jpg.sql
@@application/shared_components/files/img_persona_male04_apex_png.sql
@@application/shared_components/files/bookmarklet_min_js.sql
@@application/shared_components/files/bookmarklet_js_map.sql
@@application/plugin_settings.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/apply_session_theme_style.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/eba_ut_chart_projects_project.sql
@@application/shared_components/user_interface/lovs/font_animations.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/通用主题_面包屑.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/user_interface/shortcuts/ok_to_get_next_prev_pk_value.sql
@@application/shared_components/security/authentications/application_express.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_template_instructions.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_region_source_code.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_preview_template_options.sql
@@application/shared_components/navigation/search_config/搜索1.sql
@@application/shared_components/navigation/search_config/搜索2.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00300.sql
@@application/pages/page_00400.sql
@@application/pages/page_00401.sql
@@application/pages/page_00402.sql
@@application/pages/page_00405.sql
@@application/pages/page_00407.sql
@@application/pages/page_00422.sql
@@application/pages/page_00423.sql
@@application/pages/page_00424.sql
@@application/pages/page_00500.sql
@@application/pages/page_00700.sql
@@application/pages/page_01100.sql
@@application/pages/page_01101.sql
@@application/pages/page_01102.sql
@@application/pages/page_01103.sql
@@application/pages/page_01104.sql
@@application/pages/page_01105.sql
@@application/pages/page_01106.sql
@@application/pages/page_01107.sql
@@application/pages/page_01108.sql
@@application/pages/page_01109.sql
@@application/pages/page_01110.sql
@@application/pages/page_01111.sql
@@application/pages/page_01112.sql
@@application/pages/page_01113.sql
@@application/pages/page_01114.sql
@@application/pages/page_01115.sql
@@application/pages/page_01116.sql
@@application/pages/page_01117.sql
@@application/pages/page_01120.sql
@@application/pages/page_01121.sql
@@application/pages/page_01122.sql
@@application/pages/page_01123.sql
@@application/pages/page_01124.sql
@@application/pages/page_01201.sql
@@application/pages/page_01202.sql
@@application/pages/page_01203.sql
@@application/pages/page_01204.sql
@@application/pages/page_01205.sql
@@application/pages/page_01206.sql
@@application/pages/page_01207.sql
@@application/pages/page_01208.sql
@@application/pages/page_01209.sql
@@application/pages/page_01210.sql
@@application/pages/page_01250.sql
@@application/pages/page_01251.sql
@@application/pages/page_01301.sql
@@application/pages/page_01303.sql
@@application/pages/page_01304.sql
@@application/pages/page_01305.sql
@@application/pages/page_01306.sql
@@application/pages/page_01307.sql
@@application/pages/page_01401.sql
@@application/pages/page_01402.sql
@@application/pages/page_01403.sql
@@application/pages/page_01405.sql
@@application/pages/page_01406.sql
@@application/pages/page_01407.sql
@@application/pages/page_01410.sql
@@application/pages/page_01411.sql
@@application/pages/page_01412.sql
@@application/pages/page_01413.sql
@@application/pages/page_01500.sql
@@application/pages/page_01600.sql
@@application/pages/page_01700.sql
@@application/pages/page_01701.sql
@@application/pages/page_01710.sql
@@application/pages/page_01711.sql
@@application/pages/page_01720.sql
@@application/pages/page_01721.sql
@@application/pages/page_01800.sql
@@application/pages/page_01901.sql
@@application/pages/page_01902.sql
@@application/pages/page_01903.sql
@@application/pages/page_01905.sql
@@application/pages/page_01907.sql
@@application/pages/page_01908.sql
@@application/pages/page_01910.sql
@@application/pages/page_01911.sql
@@application/pages/page_01912.sql
@@application/pages/page_01913.sql
@@application/pages/page_01914.sql
@@application/pages/page_01915.sql
@@application/pages/page_01916.sql
@@application/pages/page_01917.sql
@@application/pages/page_01918.sql
@@application/pages/page_01919.sql
@@application/pages/page_01920.sql
@@application/pages/page_01921.sql
@@application/pages/page_01922.sql
@@application/pages/page_01923.sql
@@application/pages/page_02000.sql
@@application/pages/page_03000.sql
@@application/pages/page_03100.sql
@@application/pages/page_03110.sql
@@application/pages/page_03810.sql
@@application/pages/page_04000.sql
@@application/pages/page_06000.sql
@@application/pages/page_06100.sql
@@application/pages/page_06200.sql
@@application/pages/page_06201.sql
@@application/pages/page_06302.sql
@@application/pages/page_06303.sql
@@application/pages/page_06304.sql
@@application/pages/page_06305.sql
@@application/pages/page_06307.sql
@@application/pages/page_09901.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/upgrade_add_卡片_演示_table_and_data.sql
@@application/deployment/install/install_创建_tables.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
