prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/资料内容_新增.sql
@@application/shared_components/navigation/lists/动态菜单.sql
@@application/shared_components/navigation/lists/home_page_list.sql
@@application/shared_components/navigation/lists/archive_list.sql
@@application/shared_components/navigation/lists/authority_list.sql
@@application/shared_components/navigation/lists/report_list.sql
@@application/shared_components/navigation/lists/chart_list.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/qrcode_js.sql
@@application/shared_components/files/js_100_echarts_wordcloud_min_js.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/jquery_qrcode_min_js.sql
@@application/shared_components/files/w3_css.sql
@@application/shared_components/files/jszip_min_js.sql
@@application/shared_components/files/bootstrap_min_css.sql
@@application/shared_components/files/html2canvas_min_js.sql
@@application/shared_components/files/bootstrap_bundle_min_js.sql
@@application/shared_components/files/qrcode_logo_png.sql
@@application/shared_components/files/w3_min_css.sql
@@application/shared_components/files/qrcode_new_min_js.sql
@@application/shared_components/files/close_png.sql
@@application/shared_components/files/lightbox_css.sql
@@application/shared_components/files/lightbox_js.sql
@@application/shared_components/files/loading_gif.sql
@@application/shared_components/files/next_png.sql
@@application/shared_components/files/prev_png.sql
@@application/shared_components/files/qrcode_background_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/超级管理员.sql
@@application/shared_components/security/authorizations/系统管理员.sql
@@application/shared_components/security/authorizations/部门经理.sql
@@application/shared_components/security/authorizations/部门主管.sql
@@application/shared_components/security/authorizations/插入权限.sql
@@application/shared_components/security/authorizations/更新权限.sql
@@application/shared_components/security/authorizations/删除权限.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/ac_session.sql
@@application/shared_components/logic/application_items/appkey.sql
@@application/shared_components/logic/application_items/appsecret.sql
@@application/shared_components/logic/application_items/app_code.sql
@@application/shared_components/logic/application_items/app_env.sql
@@application/shared_components/logic/application_items/base_dept_id.sql
@@application/shared_components/logic/application_items/bpoint_button_url.sql
@@application/shared_components/logic/application_items/is_change_pswd.sql
@@application/shared_components/logic/application_items/jingbao_api_url.sql
@@application/shared_components/logic/application_items/jingbao_api_url_1.sql
@@application/shared_components/logic/application_items/jingbao_url.sql
@@application/shared_components/logic/application_items/mpf_api_url.sql
@@application/shared_components/logic/application_items/org_id.sql
@@application/shared_components/logic/application_items/org_name.sql
@@application/shared_components/logic/application_items/release_text.sql
@@application/shared_components/logic/application_items/roleid.sql
@@application/shared_components/logic/application_items/userauth.sql
@@application/shared_components/logic/application_items/userdept.sql
@@application/shared_components/logic/application_items/useremail.sql
@@application/shared_components/logic/application_items/userid.sql
@@application/shared_components/logic/application_items/userjobnumber.sql
@@application/shared_components/logic/application_items/usermobile.sql
@@application/shared_components/logic/application_items/username.sql
@@application/shared_components/logic/application_items/usertenant.sql
@@application/shared_components/logic/application_items/user_id.sql
@@application/shared_components/logic/application_computations/app_code.sql
@@application/shared_components/logic/application_computations/bpoint_button_url.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/check_status（点检状态）.sql
@@application/shared_components/user_interface/lovs/cust_first_name.sql
@@application/shared_components/user_interface/lovs/event_category_lov.sql
@@application/shared_components/user_interface/lovs/event_phenomenon_lov.sql
@@application/shared_components/user_interface/lovs/ext_org_lov.sql
@@application/shared_components/user_interface/lovs/ext_org_lov1.sql
@@application/shared_components/user_interface/lovs/fab_name.sql
@@application/shared_components/user_interface/lovs/is_support_image.sql
@@application/shared_components/user_interface/lovs/liability_type.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/maintenance_status（维保状态）.sql
@@application/shared_components/user_interface/lovs/map_area_name.sql
@@application/shared_components/user_interface/lovs/rule_type（推送规则类型）.sql
@@application/shared_components/user_interface/lovs/true_false_lov.sql
@@application/shared_components/user_interface/lovs/username_lov.sql
@@application/shared_components/user_interface/lovs/username_lov1.sql
@@application/shared_components/user_interface/lovs/user_group_asso_name.sql
@@application/shared_components/user_interface/lovs/week_month.sql
@@application/shared_components/user_interface/lovs/yes_no_lov.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/面包屑.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/html_button_legacy_apex_5_migration.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/automations/晶豹机器人推送.sql
@@application/shared_components/automations/晶豹频发事件推送_日.sql
@@application/shared_components/automations/晶豹频发事件推送_周.sql
@@application/shared_components/automations/晶豹频发事件推送_月.sql
@@application/shared_components/automations/晶点日报推送.sql
@@application/shared_components/automations/合肥升级提醒_弃用.sql
@@application/shared_components/automations/同步一线岗位人员_弃用.sql
@@application/shared_components/automations/晶豹未关闭分部门群推送_弃用.sql
@@application/shared_components/automations/运营提报推送_月.sql
@@application/shared_components/automations/运营日报推送_周.sql
@@application/shared_components/automations/运营日报推送_日.sql
@@application/shared_components/automations/积分排行版推送_日.sql
@@application/shared_components/automations/积分排行版推送_周.sql
@@application/shared_components/automations/积分排行版推送_月.sql
@@application/shared_components/automations/晶豹升级提醒_弃用.sql
@@application/shared_components/security/authentications/login_auth.sql
@@application/shared_components/security/authentications/apexappauth.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/plugins/dynamic_action/com_oracle_apex_timer.sql
@@application/shared_components/plugins/region_type/apex_fancytree_select.sql
@@application/shared_components/plugins/region_type/orclking_heat_map_chart.sql
@@application/shared_components/plugins/region_type/de_danielh_dropzone2.sql
@@application/shared_components/plugins/item_type/pl_ostrowskibartosz_apex_enhancedlovitem.sql
@@application/shared_components/data_loads/data_upload_test.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00090.sql
@@application/pages/page_00091.sql
@@application/pages/page_00092.sql
@@application/pages/page_00093.sql
@@application/pages/page_00094.sql
@@application/pages/page_00095.sql
@@application/pages/page_00096.sql
@@application/pages/page_00097.sql
@@application/pages/page_00098.sql
@@application/pages/page_00099.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00105.sql
@@application/pages/page_00106.sql
@@application/pages/page_00107.sql
@@application/pages/page_00108.sql
@@application/pages/page_00109.sql
@@application/pages/page_00110.sql
@@application/pages/page_00111.sql
@@application/pages/page_00112.sql
@@application/pages/page_00113.sql
@@application/pages/page_00114.sql
@@application/pages/page_00115.sql
@@application/pages/page_00116.sql
@@application/pages/page_00117.sql
@@application/pages/page_00118.sql
@@application/pages/page_00119.sql
@@application/pages/page_00120.sql
@@application/pages/page_00121.sql
@@application/pages/page_00122.sql
@@application/pages/page_00123.sql
@@application/pages/page_00124.sql
@@application/pages/page_00125.sql
@@application/pages/page_00126.sql
@@application/pages/page_00127.sql
@@application/pages/page_00128.sql
@@application/pages/page_00129.sql
@@application/pages/page_00130.sql
@@application/pages/page_00131.sql
@@application/pages/page_00132.sql
@@application/pages/page_00133.sql
@@application/pages/page_00134.sql
@@application/pages/page_00135.sql
@@application/pages/page_00136.sql
@@application/pages/page_00137.sql
@@application/pages/page_00138.sql
@@application/pages/page_00139.sql
@@application/pages/page_00140.sql
@@application/pages/page_00141.sql
@@application/pages/page_00142.sql
@@application/pages/page_00143.sql
@@application/pages/page_00144.sql
@@application/pages/page_00145.sql
@@application/pages/page_00146.sql
@@application/pages/page_00147.sql
@@application/pages/page_00148.sql
@@application/pages/page_00149.sql
@@application/pages/page_00150.sql
@@application/pages/page_00151.sql
@@application/pages/page_00152.sql
@@application/pages/page_00153.sql
@@application/pages/page_00154.sql
@@application/pages/page_00155.sql
@@application/pages/page_00156.sql
@@application/pages/page_00157.sql
@@application/pages/page_00158.sql
@@application/pages/page_00159.sql
@@application/pages/page_00160.sql
@@application/pages/page_00161.sql
@@application/pages/page_00162.sql
@@application/pages/page_00163.sql
@@application/pages/page_00164.sql
@@application/pages/page_00165.sql
@@application/pages/page_00166.sql
@@application/pages/page_00167.sql
@@application/pages/page_00168.sql
@@application/pages/page_00169.sql
@@application/pages/page_00170.sql
@@application/pages/page_00171.sql
@@application/pages/page_00172.sql
@@application/pages/page_00173.sql
@@application/pages/page_00174.sql
@@application/pages/page_00175.sql
@@application/pages/page_00176.sql
@@application/pages/page_00177.sql
@@application/pages/page_00178.sql
@@application/pages/page_00179.sql
@@application/pages/page_00180.sql
@@application/pages/page_00181.sql
@@application/pages/page_00182.sql
@@application/pages/page_00183.sql
@@application/pages/page_00184.sql
@@application/pages/page_00185.sql
@@application/pages/page_00186.sql
@@application/pages/page_00187.sql
@@application/pages/page_00188.sql
@@application/pages/page_00189.sql
@@application/pages/page_00190.sql
@@application/pages/page_00191.sql
@@application/pages/page_00192.sql
@@application/pages/page_00193.sql
@@application/pages/page_00194.sql
@@application/pages/page_00195.sql
@@application/pages/page_00196.sql
@@application/pages/page_00197.sql
@@application/pages/page_00198.sql
@@application/pages/page_00199.sql
@@application/pages/page_00200.sql
@@application/pages/page_00201.sql
@@application/pages/page_00202.sql
@@application/pages/page_00203.sql
@@application/pages/page_00204.sql
@@application/pages/page_00205.sql
@@application/pages/page_00206.sql
@@application/pages/page_00207.sql
@@application/pages/page_00208.sql
@@application/pages/page_00209.sql
@@application/pages/page_00210.sql
@@application/pages/page_00211.sql
@@application/pages/page_00212.sql
@@application/pages/page_00213.sql
@@application/pages/page_00214.sql
@@application/pages/page_00215.sql
@@application/pages/page_00216.sql
@@application/pages/page_00217.sql
@@application/pages/page_00218.sql
@@application/pages/page_00219.sql
@@application/pages/page_00220.sql
@@application/pages/page_00221.sql
@@application/pages/page_00222.sql
@@application/pages/page_00223.sql
@@application/pages/page_00224.sql
@@application/pages/page_00225.sql
@@application/pages/page_00226.sql
@@application/pages/page_00227.sql
@@application/pages/page_00228.sql
@@application/pages/page_00229.sql
@@application/pages/page_00230.sql
@@application/pages/page_00231.sql
@@application/pages/page_00232.sql
@@application/pages/page_00233.sql
@@application/pages/page_00234.sql
@@application/pages/page_00235.sql
@@application/pages/page_00236.sql
@@application/pages/page_00237.sql
@@application/pages/page_00238.sql
@@application/pages/page_00239.sql
@@application/pages/page_00240.sql
@@application/pages/page_00241.sql
@@application/pages/page_00242.sql
@@application/pages/page_00243.sql
@@application/pages/page_00244.sql
@@application/pages/page_00245.sql
@@application/pages/page_00246.sql
@@application/pages/page_00247.sql
@@application/pages/page_00248.sql
@@application/pages/page_00249.sql
@@application/pages/page_00250.sql
@@application/pages/page_00251.sql
@@application/pages/page_00252.sql
@@application/pages/page_00253.sql
@@application/pages/page_00254.sql
@@application/pages/page_00255.sql
@@application/pages/page_00256.sql
@@application/pages/page_00257.sql
@@application/pages/page_00258.sql
@@application/pages/page_00259.sql
@@application/pages/page_00260.sql
@@application/pages/page_00261.sql
@@application/pages/page_00262.sql
@@application/pages/page_00263.sql
@@application/pages/page_00264.sql
@@application/pages/page_00265.sql
@@application/pages/page_00266.sql
@@application/pages/page_00267.sql
@@application/pages/page_00268.sql
@@application/pages/page_00269.sql
@@application/pages/page_00270.sql
@@application/pages/page_00271.sql
@@application/pages/page_00272.sql
@@application/pages/page_00273.sql
@@application/pages/page_00274.sql
@@application/pages/page_00275.sql
@@application/pages/page_00276.sql
@@application/pages/page_00277.sql
@@application/pages/page_00278.sql
@@application/pages/page_00279.sql
@@application/pages/page_00280.sql
@@application/pages/page_00281.sql
@@application/pages/page_00282.sql
@@application/pages/page_00283.sql
@@application/pages/page_00284.sql
@@application/pages/page_00285.sql
@@application/pages/page_00287.sql
@@application/pages/page_00288.sql
@@application/pages/page_00292.sql
@@application/pages/page_00293.sql
@@application/pages/page_00294.sql
@@application/pages/page_00295.sql
@@application/pages/page_00296.sql
@@application/pages/page_00297.sql
@@application/pages/page_00298.sql
@@application/pages/page_00299.sql
@@application/pages/page_00300.sql
@@application/pages/page_00301.sql
@@application/pages/page_00302.sql
@@application/pages/page_00303.sql
@@application/pages/page_00304.sql
@@application/pages/page_00305.sql
@@application/pages/page_00306.sql
@@application/pages/page_00307.sql
@@application/pages/page_00308.sql
@@application/pages/page_01000.sql
@@application/pages/page_09999.sql
@@application/pages/page_10009.sql
@@application/pages/page_99999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
