                                                                                                                                                                                                                                                                                 
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CALL_MONITOR_REPORT_V" ("MAINID", "CALLTIME", "CALLDATE", "CALLSOURCE", "CALL_EXT_USER_ID", "CALLER", "CALLED_EXT_USER_ID", "BECALLER", "IS_SUCCESS", "DURATION", "FAB_NAME", "LINE_NAME", "OP_NAME", "TENANT_ID") AS     
  SELECT B.CALL_MONITOR_ASSO_ID                 AS MAINID,                                                                                                                                                                                                                       
       A.CREATION_DATE                        AS CALLTIME,                                                                                                                                                                                                                       
--TRUNC(A.CREATION_DATE) AS CALLDATE,                                                                                                                                                                                                                                            
       to_char(A.CREATION_DATE, 'YYYY/MM/DD') as CALLDATE,                                                                                                                                                                                                                       
       A.SUBMIT_SOURCE                        AS CALLSOURCE,                                                                                                                                                                                                                     
       A.CALL_EXT_USER_ID,                                                                                                                                                                                                                                                       
       D.NAME                                 AS CALLER,                                                                                                                                                                                                                         
       B.CALLED_EXT_USER_ID,                                                                                                                                                                                                                                                     
       E.NAME                                 AS BECALLER,                                                                                                                                                                                                                       
       B.IS_SUCCESS,                                                                                                                                                                                                                                                             
       NVL(B.DURATION, 0)                     AS DURATION,                                                                                                                                                                                                                       
       C.FAB_NAME                             AS FAB_NAME,                                                                                                                                                                                                                       
       C.MAP_AREA_Y_NAME                      AS LINE_NAME,                                                                                                                                                                                                                      
       C.MAP_AREA_X_NAME                      AS OP_NAME,                                                                                                                                                                                                                        
       A.TENANT_ID                                                                                                                                                                                                                                                               
FROM TENANT_CALL_MONITOR A                                                                                                                                                                                                                                                       
         INNER JOIN TENANT_CALL_MONITOR_ASSO B ON A.CALL_MONITOR_ID = B.CALL_MONITOR_ID                                                                                                                                                                                          
         LEFT JOIN FND_MAPS_AREAS_ASSO_V C ON C.MAP_ID = B.MAP_ID                                                                                                                                                                                                                
         LEFT JOIN MPF_USER_DEPT_MAIN_ASSO_V D ON D.EXT_USER_ID = A.CALL_EXT_USER_ID                                                                                                                                                                                             
         LEFT JOIN MPF_USER_DEPT_MAIN_ASSO_V E ON E.EXT_USER_ID = B.CALLED_EXT_USER_ID                                                                                                                                                                                           
--LEFT JOIN TENANT_EXT_USERS_ORG_MAIN_ASSO_V D ON D.EXT_USER_ID = A.CALL_EXT_USER_ID                                                                                                                                                                                             
--LEFT JOIN TENANT_EXT_USERS_ORG_MAIN_ASSO_V E ON E.EXT_USER_ID = B.CALLED_EXT_USER_ID                                                                                                                                                                                           
WHERE A.CREATION_DATE > (SYSDATE - 10)                                                                                                                                                                                                                                           
ORDER BY A.CREATION_DATE DESC;                                                                                                                                                                                                                                                   

