                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FND_MAPS_AREAS_ASSO_V" ("BASE_ID", "BASE_NAME", "MAP_ID", "FAB_ID", "FAB_NAME", "FAB_CODE", "SYSTEM_CODE", "ORG_GROUP_CODE", "MANAGE_EXT_ORG_ID", "TENANT_ID", "MAP_AREA_Y_ID", "MAP_AREA_Y_NAME", "MAP_AREA_Y_CODE", "MAP_AREA_X_ID", "MAP_AREA_X_NAME", "MAP_AREA_X_CODE", "FAB_IS_ENABLE", "AREA_X_IS_ENABLE", "AREA_Y_IS_ENABLE", "MAP_IS_ENABLE", "IS_ENABLE", "BASE_DEPT_ID") AS     
  select b.BASE_ID,                                                                                                                                                                                                                                                                                                                                                                                                                               
       b.NAME                                                        as BASE_NAME,                                                                                                                                                                                                                                                                                                                                                                
       map.MAP_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                
       map.FAB_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                
       f.NAME                                                        as fab_name,                                                                                                                                                                                                                                                                                                                                                                 
       f.SYSTEM_CODE                                                 as fab_code,                                                                                                                                                                                                                                                                                                                                                                 
       f.SYSTEM_CODE || '#' || y.SYSTEM_CODE || '#' || x.SYSTEM_CODE as system_code,                                                                                                                                                                                                                                                                                                                                                              
       f.ORG_GROUP_CODE                                              as ORG_GROUP_CODE,                                                                                                                                                                                                                                                                                                                                                           
       f.MANAGE_EXT_ORG_ID,                                                                                                                                                                                                                                                                                                                                                                                                                       
       map.TENANT_ID,                                                                                                                                                                                                                                                                                                                                                                                                                             
       map.MAP_AREA_Y_ID,                                                                                                                                                                                                                                                                                                                                                                                                                         
       y.NAME                                                        as map_area_y_name,                                                                                                                                                                                                                                                                                                                                                          
       y.SYSTEM_CODE                                                 as map_area_y_code,                                                                                                                                                                                                                                                                                                                                                          
       map.MAP_AREA_X_ID,                                                                                                                                                                                                                                                                                                                                                                                                                         
       x.NAME                                                        as map_area_x_name,                                                                                                                                                                                                                                                                                                                                                          
       x.SYSTEM_CODE                                                 as map_area_x_code,                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       f.IS_ENABLE                                                   as fab_is_enable,                                                                                                                                                                                                                                                                                                                                                            
       y.IS_ENABLE                                                   as area_x_is_enable,                                                                                                                                                                                                                                                                                                                                                         
       x.IS_ENABLE                                                   as area_y_is_enable,                                                                                                                                                                                                                                                                                                                                                         
       map.IS_ENABLE                                                 as map_is_enable,                                                                                                                                                                                                                                                                                                                                                            
       DECODE(nvl(f.IS_ENABLE, 0), 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                          
              DECODE(nvl(y.IS_ENABLE, 0), 0, 0,                                                                                                                                                                                                                                                                                                                                                                                                   
                     DECODE(nvl(x.IS_ENABLE, 0), 0, 0,                                                                                                                                                                                                                                                                                                                                                                                            
                            DECODE(nvl(map.IS_ENABLE, 0), 0, 0, 1)                                                                                                                                                                                                                                                                                                                                                                                
                         )                                                                                                                                                                                                                                                                                                                                                                                                                        
                  )                                                                                                                                                                                                                                                                                                                                                                                                                               
           )                                                         as is_enable,                                                                                                                                                                                                                                                                                                                                                                
       map.BASE_DEPT_ID                                                                                                                                                                                                                                                                                                                                                                                                                           
from FND_MAPS map                                                                                                                                                                                                                                                                                                                                                                                                                                 
         inner join FND_FAB f on map.FAB_ID = f.FAB_ID and f.DEL_FLAG = 0                                                                                                                                                                                                                                                                                                                                                                         
         inner join FND_AREAS x on x.AREA_ID = map.MAP_AREA_X_ID and x.DEL_FLAG = 0                                                                                                                                                                                                                                                                                                                                                               
         inner join FND_AREAS y on y.AREA_ID = map.MAP_AREA_Y_ID and y.DEL_FLAG = 0                                                                                                                                                                                                                                                                                                                                                               
         left join TENANT_BASE b on b.BASE_ID = f.BASE_ID and b.DEL_FLAG = 0                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
order by y.SORT_NUM, x.SORT_NUM;                                                                                                                                                                                                                                                                                                                                                                                                                  

