                                                                                                                                                                                                                                                                                                                                                               
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MAPS_WORK_STATION_V" ("MAPS_WORK_STATION_ID", "MAP_ID", "WORK_STATION_ID", "NAME", "CODE", "DAY_MAX_USERS_COUNT", "NIGHT_MAX_USERS_COUNT", "MAP_X_PIXEL", "MAP_Y_PIXEL", "TENANT_ID", "IS_ENABLE", "FAB_ID", "FAB_NAME", "MAP_AREA_X_ID", "MAP_AREA_X_NAME", "MAP_AREA_Y_ID", "MAP_AREA_Y_NAME") AS     
  select s.MAPS_WORK_STATION_ID,                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                               
       s.MAP_ID,                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                               
       s.WORK_STATION_ID,                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                               
       w.NAME,                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                               
       w.CODE,                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                               
       s.DAY_MAX_USERS_COUNT,                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                               
       s.NIGHT_MAX_USERS_COUNT,                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                               
       s.MAP_X_PIXEL,                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                               
       s.MAP_Y_PIXEL,                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                               
       s.TENANT_ID,                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                               
       s.IS_ENABLE,                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                               
       m.FAB_ID,                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                               
       m.FAB_NAME,                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                               
       m.MAP_AREA_X_ID,                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                               
       m.MAP_AREA_X_NAME,                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                               
       m.MAP_AREA_Y_ID,                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                               
       m.MAP_AREA_Y_NAME                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                               
from FND_MAPS_WORK_STATION s                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                               
         inner join FND_WORK_STATION w on w.WORK_STATION_ID = s.WORK_STATION_ID                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                               
         inner join FND_MAPS_AREAS_ASSO_V m on m.MAP_ID = s.MAP_ID                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                               
where s.IS_HIDE = 0                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                               
  and DEL_FLAG = 0;                                                                                                                                                                                                                                                                                                                                            

