                                                                                                                                                                                                                                                                                                          
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MPF_SHARE_USER_V" ("EXT_USER_ID", "TENANT_ID", "SYNC_USER_ID", "UNION_ID", "TITLE", "NAME", "AVATAR", "STATE_CODE", "MOBILE", "JOB_NUMBER", "EMAIL", "IS_LEAVE", "HIRED_DATE", "LEADER_SYNC_USER_ID", "LEADER_EXT_USER_ID", "BASE_DEPT_ID") AS     
  select USER_ID              AS         EXT_USER_ID,                                                                                                                                                                                                                                                     
       TENANT_ID,                                                                                                                                                                                                                                                                                         
       EXTRA_USER_ID        AS         SYNC_USER_ID,                                                                                                                                                                                                                                                      
       UNION_ID,                                                                                                                                                                                                                                                                                          
       TITLE,                                                                                                                                                                                                                                                                                             
       NAME,                                                                                                                                                                                                                                                                                              
       AVATAR,                                                                                                                                                                                                                                                                                            
       STATE_CODE,                                                                                                                                                                                                                                                                                        
       MOBILE,                                                                                                                                                                                                                                                                                            
       JOB_NUMBER,                                                                                                                                                                                                                                                                                        
       EMAIL,                                                                                                                                                                                                                                                                                             
       IS_LEAVE,                                                                                                                                                                                                                                                                                          
       HIRED_DATE,                                                                                                                                                                                                                                                                                        
       LEADER_EXTRA_USER_ID AS         LEADER_SYNC_USER_ID,                                                                                                                                                                                                                                               
       LEADER_USER_ID       as         LEADER_EXT_USER_ID,                                                                                                                                                                                                                                                
       BASE_DEPT_ID                                                                                                                                                                                                                                                                                       
from MPF_SHARE_BASIC_USER_INFO_V;                                                                                                                                                                                                                                                                         

