                                                                                                                                                                                                                                                                        
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TENANT_ORG_GROUP_ASSO_V" ("ORG_GROUP_ID", "NAME", "FAB_ID", "CODE", "ORG_GROUP_ASSO_ID", "SORT_NUM", "TENANT_ID", "EXT_ORG_NAME", "PARENT_ID", "EXT_ORG_ID", "LAYOUT_CODE", "LAYOUT_NUM", "BASE_DEPT_ID") AS     
  select og.ORG_GROUP_ID,                                                                                                                                                                                                                                               
       og.NAME,                                                                                                                                                                                                                                                         
       og.FAB_ID,                                                                                                                                                                                                                                                       
       og.CODE,                                                                                                                                                                                                                                                         
       asso.ORG_GROUP_ASSO_ID,                                                                                                                                                                                                                                          
       asso.SORT_NUM,                                                                                                                                                                                                                                                   
       asso.TENANT_ID,                                                                                                                                                                                                                                                  
       org.NAME           as EXT_ORG_NAME,                                                                                                                                                                                                                              
       org.PARENT_DEPT_ID AS PARENT_ID,                                                                                                                                                                                                                                 
       asso.EXT_ORG_ID,                                                                                                                                                                                                                                                 
       asso.LAYOUT_CODE,                                                                                                                                                                                                                                                
       asso.LAYOUT_NUM,                                                                                                                                                                                                                                                 
       og.BASE_DEPT_ID                                                                                                                                                                                                                                                  
from TENANT_ORG_GROUP_ASSO asso                                                                                                                                                                                                                                         
         inner join MPF.SHARE_BASIC_DEPT_V org on asso.EXT_ORG_ID = org.DEPT_ID                                                                                                                                                                                         
         inner join TENANT_ORG_GROUP og on og.ORG_GROUP_ID = asso.ORG_GROUP_ID and og.DEL_FLAG = 0;                                                                                                                                                                     

