                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TENANT_EXT_USERS_ORG_MAIN_ASSO_V" ("EXT_USER_ID", "SYNC_USER_ID", "CREATED_BY", "CREATION_DATE", "UPDATED_BY", "UPDATE_DATE", "REMARK", "TENANT_ID", "UNIONID", "TITLE", "NAME", "AVATAR", "STATE_CODE", "MOBILE", "JOB_NUMBER", "EMAIL", "TYPE", "IS_EXT_USER", "PASSWORD", "STAFF_LEVEL", "HIRED_DATE", "LEADER_EXT_USER_ID", "LEADER_SYNC_USER_ID", "LEADER_EXT_USER_NAME", "GENDER", "JOB_LEVEL", "JOB_LEVEL_CODE", "EXT_ORG_ID", "EXT_ORG_NAME", "LAST_LOGIN_DATE") AS     
  select u.ext_user_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
       u.SYNC_USER_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
       u.created_by,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       u.creation_date,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
       u.updated_by,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       u.update_date,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       u.remark,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
       u.tenant_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
       u.unionid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
       u.title,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
       u.name,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
       u.avatar,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
       u.state_code,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       u.mobile,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
       u.job_number,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       u.email,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
       u.type,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
       u.is_ext_user,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       u.password,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
       u.STAFF_LEVEL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       u.HIRED_DATE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       u.LEADER_EXT_USER_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
       lu.SYNC_USER_ID                as LEADER_SYNC_USER_ID,                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
       lu.NAME                        as LEADER_EXT_USER_NAME,                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
       u.GENDER,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
       uo.job_level,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       uo.JOB_LEVEL_CODE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
       uo.ext_org_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       SELECT_ORG_NAME(uo.EXT_ORG_ID) as ext_org_name,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
       u.LAST_LOGIN_DATE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
from TENANT_EXT_USERS u                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
         left join TENANT_EXT_USER_ORG_ASSO uo on uo.EXT_USER_ID = u.EXT_USER_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                       
         left join TENANT_EXT_USERS lu on lu.EXT_USER_ID = u.LEADER_EXT_USER_ID                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
where u.DEL_FLAG = 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  and u.IS_LEAVE = 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  and RELATED_TYPE = 'MAIN';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

