                                                                                                                                                                                                                                                                                                                                                                                                                           
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TENANT_ISSUE_REPORT_V" ("MAIN_ID", "SUBMIT_NAME", "SUBMIT_DEP", "SUBMIT_SOURCE", "DESCRIPTION", "STATUS", "DSTATUS", "CHILD_ID", "FOLLOWER", "FOLLOWER_DEP", "EXT_ORG_ID", "FAB_NAME", "OP_NAME", "L_NAME", "CREATE_DATE", "CREATION_TIME", "ANSWER_TIME", "DEAL_TIME", "IS_END", "END_TIME", "BEGIN_TIME", "CLOSE_TIME", "ST", "TENANT_ID", "BASE_DEPT_ID") AS     
  select A.EVENT_ID                             AS MAIN_ID,                                                                                                                                                                                                                                                                                                                                                                
       D.NAME                                 AS SUBMIT_NAME,                                                                                                                                                                                                                                                                                                                                                              
       D.ext_org_name                         AS SUBMIT_DEP,                                                                                                                                                                                                                                                                                                                                                               
       A.SUBMIT_SOURCE,                                                                                                                                                                                                                                                                                                                                                                                                    
       A.description,                                                                                                                                                                                                                                                                                                                                                                                                      
       A.STATUS,                                                                                                                                                                                                                                                                                                                                                                                                           
       B.STATUS                               AS DSTATUS,                                                                                                                                                                                                                                                                                                                                                                  
       B.EVENT_FOLLOW_ID                         CHILD_ID,                                                                                                                                                                                                                                                                                                                                                                 
       C.NAME                                 AS FOLLOWER,                                                                                                                                                                                                                                                                                                                                                                 
       C.ext_org_name                         AS FOLLOWER_DEP,                                                                                                                                                                                                                                                                                                                                                             
       C.EXT_ORG_ID,                                                                                                                                                                                                                                                                                                                                                                                                       
       E.fab_name,                                                                                                                                                                                                                                                                                                                                                                                                         
       E.map_area_x_name                      AS OP_NAME,                                                                                                                                                                                                                                                                                                                                                                  
       E.MAP_AREA_Y_NAME                      AS L_NAME,                                                                                                                                                                                                                                                                                                                                                                   
       to_char(A.CREATION_DATE, 'YYYY/MM/DD') AS CREATE_DATE,                                                                                                                                                                                                                                                                                                                                                              
       A.CREATION_DATE                           CREATION_TIME,                                                                                                                                                                                                                                                                                                                                                            
       B.CREATION_DATE                           "ANSWER_TIME",                                                                                                                                                                                                                                                                                                                                                            
       B.UPDATE_DATE                             "DEAL_TIME",                                                                                                                                                                                                                                                                                                                                                              
       0                                         IS_END,                                                                                                                                                                                                                                                                                                                                                                   
       A.END_TIME,                                                                                                                                                                                                                                                                                                                                                                                                         
       A.BEGIN_TIME,                                                                                                                                                                                                                                                                                                                                                                                                       
       A.UPDATE_DATE                             CLOSE_TIME,                                                                                                                                                                                                                                                                                                                                                               
       (                                                                                                                                                                                                                                                                                                                                                                                                                   
           CASE                                                                                                                                                                                                                                                                                                                                                                                                            
               WHEN A.END_TIME IS NOT NULL THEN                                                                                                                                                                                                                                                                                                                                                                            
                   ROUND(TO_NUMBER(a.END_TIME - A.BEGIN_TIME) * 24, 2)                                                                                                                                                                                                                                                                                                                                                     
               ELSE 0                                                                                                                                                                                                                                                                                                                                                                                                      
               END                                                                                                                                                                                                                                                                                                                                                                                                         
           )                                     ST,                                                                                                                                                                                                                                                                                                                                                                       
       A.TENANT_ID,                                                                                                                                                                                                                                                                                                                                                                                                        
       A.BASE_DEPT_ID                                                                                                                                                                                                                                                                                                                                                                                                      
FROM TENANT_EVENT A                                                                                                                                                                                                                                                                                                                                                                                                        
         INNER JOIN TENANT_EVENT_FOLLOW_USERS B ON A.EVENT_ID = B.EVENT_ID and b.BASE_DEPT_ID=a.BASE_DEPT_ID                                                                                                                                                                                                                                                                                                               
         INNER JOIN MPF_USER_DEPT_MAIN_ASSO_V C ON B.EXT_USER_ID = C.EXT_USER_ID and b.BASE_DEPT_ID=c.BASE_DEPT_ID                                                                                                                                                                                                                                                                                                         
         INNER JOIN MPF_USER_DEPT_MAIN_ASSO_V D ON A.SUBMIT_USER_ID = D.EXT_USER_ID and d.BASE_DEPT_ID=a.BASE_DEPT_ID                                                                                                                                                                                                                                                                                                      
         LEFT JOIN FND_MAPS_AREAS_ASSO_V E ON A.MAP_ID = E.MAP_ID and e.BASE_DEPT_ID=a.BASE_DEPT_ID                                                                                                                                                                                                                                                                                                                        
WHERE a.CREATION_DATE > trunc(sysdate, 'yyyy');                                                                                                                                                                                                                                                                                                                                                                            

