prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/数据分析.sql
@@application/shared_components/navigation/lists/更新反馈.sql
@@application/shared_components/navigation/lists/主页.sql
@@application/shared_components/navigation/lists/文件库.sql
@@application/shared_components/navigation/lists/系统设置.sql
@@application/shared_components/navigation/lists/操作手册与问题反馈.sql
@@application/shared_components/navigation/lists/导航菜单.sql
@@application/shared_components/navigation/lists/导航栏.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/系统需求编辑权限_查询角色等级（返回布尔值）.sql
@@application/shared_components/security/authorizations/系统需求编辑权限_查询角色code（返回布尔值）.sql
@@application/shared_components/security/authorizations/管理权限.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/get_system_options.sql
@@application/shared_components/logic/application_processes/set_current_system.sql
@@application/shared_components/logic/application_items/app_code.sql
@@application/shared_components/logic/application_items/app_env.sql
@@application/shared_components/logic/application_items/dian_user_id.sql
@@application/shared_components/logic/application_items/mpf_user_id.sql
@@application/shared_components/logic/application_items/page.sql
@@application/shared_components/logic/application_items/pm_project_id.sql
@@application/shared_components/logic/application_items/release_text.sql
@@application/shared_components/logic/application_items/role_code.sql
@@application/shared_components/logic/application_items/role_id.sql
@@application/shared_components/logic/application_items/role_level.sql
@@application/shared_components/logic/application_items/sts_appkey.sql
@@application/shared_components/logic/application_items/sts_appsecret.sql
@@application/shared_components/logic/application_items/sts_jy_api_url.sql
@@application/shared_components/logic/application_items/system_id.sql
@@application/shared_components/logic/application_items/user_id.sql
@@application/shared_components/logic/application_items/user_job_number.sql
@@application/shared_components/logic/application_items/user_name.sql
@@application/shared_components/logic/application_items/user_tenant.sql
@@application/shared_components/logic/application_computations/page.sql
@@application/shared_components/logic/application_computations/app_code.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/base（基地）.sql
@@application/shared_components/user_interface/lovs/basic_user（晶台用户）.sql
@@application/shared_components/user_interface/lovs/feedback_status（反馈状态）.sql
@@application/shared_components/user_interface/lovs/feedback_type（处理方案）.sql
@@application/shared_components/user_interface/lovs/file_status（文件状态）.sql
@@application/shared_components/user_interface/lovs/im_level（重要等级）.sql
@@application/shared_components/user_interface/lovs/is_enable（是否启用）.sql
@@application/shared_components/user_interface/lovs/plans_file_type_计划归档类型_无立即归档.sql
@@application/shared_components/user_interface/lovs/plans_file_type（计划归档类型）.sql
@@application/shared_components/user_interface/lovs/req_type（需求类型）.sql
@@application/shared_components/user_interface/lovs/sts_sys_config（可见范围）.sql
@@application/shared_components/user_interface/lovs/sts_sys_config（权限类型）.sql
@@application/shared_components/user_interface/lovs/sts_user（后台用户）.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/面包屑.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_账户.sql
@@application/shared_components/security/authentications/sts_login.sql
@@application/shared_components/plugins/region_type/de_danielh_dropzone2.sql
@@application/shared_components/plugins/dynamic_action/refresh_rds_region.sql
@@application/shared_components/plugins/region_type/com_fos_image_slider.sql
@@application/shared_components/plugins/dynamic_action/com_enhanceigwithtreegrid_plugin.sql
@@application/shared_components/plugins/template_component/theme_42_avatar.sql
@@application/shared_components/plugins/template_component/theme_42_badge.sql
@@application/shared_components/plugins/template_component/theme_42_button.sql
@@application/shared_components/plugins/template_component/theme_42_comments.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/region_type/com_github_ogobrecht_dhtmlxgantt.sql
@@application/shared_components/plugins/region_type/apex_fancytree_select.sql
@@application/shared_components/data_loads/导入模板.sql
@@application/shared_components/data_loads/质量成本_成本数据.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00008.sql
@@application/pages/page_00010.sql
@@application/pages/page_00013.sql
@@application/pages/page_00015.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00120.sql
@@application/pages/page_00121.sql
@@application/pages/page_00122.sql
@@application/pages/page_00123.sql
@@application/pages/page_00124.sql
@@application/pages/page_00125.sql
@@application/pages/page_00126.sql
@@application/pages/page_00127.sql
@@application/pages/page_00131.sql
@@application/pages/page_00132.sql
@@application/pages/page_00133.sql
@@application/pages/page_00134.sql
@@application/pages/page_00135.sql
@@application/pages/page_00136.sql
@@application/pages/page_00137.sql
@@application/pages/page_00138.sql
@@application/pages/page_00139.sql
@@application/pages/page_00140.sql
@@application/pages/page_00141.sql
@@application/pages/page_00142.sql
@@application/pages/page_00143.sql
@@application/pages/page_00144.sql
@@application/pages/page_00145.sql
@@application/pages/page_00146.sql
@@application/pages/page_00147.sql
@@application/pages/page_00148.sql
@@application/pages/page_00149.sql
@@application/pages/page_00150.sql
@@application/pages/page_00151.sql
@@application/pages/page_00152.sql
@@application/pages/page_00153.sql
@@application/pages/page_00154.sql
@@application/pages/page_00155.sql
@@application/pages/page_00156.sql
@@application/pages/page_00220.sql
@@application/pages/page_00221.sql
@@application/pages/page_00222.sql
@@application/pages/page_00223.sql
@@application/pages/page_00224.sql
@@application/pages/page_00225.sql
@@application/pages/page_00226.sql
@@application/pages/page_00230.sql
@@application/pages/page_00901.sql
@@application/pages/page_00902.sql
@@application/pages/page_00903.sql
@@application/pages/page_00904.sql
@@application/pages/page_00905.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
