                                                                                                                                                                                                                                                                                                    
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MPF_BASIC_JA_DING_USER_V" ("USER_ID", "CREATION_DATE", "UPDATE_DATE", "IS_LEAVE", "TENANT_ID", "UNION_ID", "TITLE", "NAME", "AVATAR", "STATE_CODE", "MOBILE", "JOB_NUMBER", "EMAIL", "HIRED_DATE", "MANAGER_USER_ID", "DEPT_IDS") AS     
  select "USER_ID",                                                                                                                                                                                                                                                                                 
       "CREATION_DATE",                                                                                                                                                                                                                                                                             
       "UPDATE_DATE",                                                                                                                                                                                                                                                                               
       "IS_LEAVE",                                                                                                                                                                                                                                                                                  
       1 as TENANT_ID,                                                                                                                                                                                                                                                                              
       "UNION_ID",                                                                                                                                                                                                                                                                                  
       "TITLE",                                                                                                                                                                                                                                                                                     
       "NAME",                                                                                                                                                                                                                                                                                      
       "AVATAR",                                                                                                                                                                                                                                                                                    
       "STATE_CODE",                                                                                                                                                                                                                                                                                
       "MOBILE",                                                                                                                                                                                                                                                                                    
       "JOB_NUMBER",                                                                                                                                                                                                                                                                                
       "EMAIL",                                                                                                                                                                                                                                                                                     
       "HIRED_DATE",                                                                                                                                                                                                                                                                                
       "MANAGER_USER_ID",                                                                                                                                                                                                                                                                           
       "DEPT_IDS"                                                                                                                                                                                                                                                                                   
from SHARE_BASIC_JA_DING_USER_V@MPF_PROD_DBLINK;                                                                                                                                                                                                                                                    

